version: '3'

services:
  db:
    build:
      context: ./db
    container_name: db
    image: marlonleiteal/postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data
    tty: true
    networks:
      - node-network
  app:
    build:
      context: ./node
    container_name: app
    image: marlonleiteal/node
    entrypoint: wait-for db:5432 -t 40 -- /tmp/start.sh
    links:
      - db
    volumes:
      - ./node:/home/node/app
    depends_on:
      - db
    networks:
      - node-network
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    image: marlonleiteal/nginx
    depends_on:
      - db
      - app
    ports:
      - "8080:80"
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
volumes:
  db:
    driver: local
